# Each exercise: equipment = list of equipment that unlocks it ("None" = bodyweight, always available)
# location = ["Gym","Home"] where it can be performed
# difficulty = Beginner/Intermediate/Advanced
# base_cal = calories burned per set (avg person, scaled later by bodyweight)
# contraindications = medical conditions that should exclude this exercise

EXERCISES = {
    "Chest": [
        {"name": "Push-Up", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 6, "contraindications": [],
         "description": "Lower your body to the floor keeping a straight line, then push back up.\nKeep core tight and elbows at 45 degrees."},
        {"name": "Incline Push-Up", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 5, "contraindications": [],
         "description": "Place hands on a bench or step and perform a push-up at an incline.\nReduces load, great for beginners."},
        {"name": "Dumbbell Chest Press", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 9, "contraindications": [],
         "description": "Lie on a bench and press dumbbells upward until arms are extended.\nLower slowly to chest level."},
        {"name": "Bench Press", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 10, "contraindications": [],
         "description": "Lie on a flat bench and press the barbell upward until your arms are fully extended.\nControl the bar on the way down to chest level."},
        {"name": "Dumbbell Fly", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 7, "contraindications": [],
         "description": "Lie on a bench and open arms wide with a slight elbow bend, lowering dumbbells.\nSqueeze chest to bring them back together."},
        {"name": "Chest Dip", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 9, "contraindications": [],
         "description": "Lower your body between parallel bars until elbows reach 90 degrees.\nPush back up leaning slightly forward to target chest."},
    ],
    "Back": [
        {"name": "Resistance Band Row", "equipment": ["Resistance Bands"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 6, "contraindications": [],
         "description": "Anchor a band and pull the handles toward your torso, squeezing shoulder blades.\nKeep back straight throughout."},
        {"name": "Superman Hold", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "Lie face down and lift arms and legs off the floor simultaneously.\nHold briefly to engage lower back muscles."},
        {"name": "Lat Pulldown", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 8, "contraindications": [],
         "description": "Pull the bar down toward your chest on a cable machine, squeezing the lats.\nControl the return to full arm extension."},
        {"name": "Seated Cable Row", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 8, "contraindications": ["Back Pain"],
         "description": "Pull the cable handle toward your torso while seated, keeping back upright.\nSqueeze shoulder blades at the end range."},
        {"name": "Dumbbell Bent-Over Row", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 8, "contraindications": ["Back Pain"],
         "description": "Hinge at the hips and row dumbbells toward your waist.\nKeep spine neutral and avoid rounding the back."},
        {"name": "Machine Row", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Beginner",
         "base_cal": 7, "contraindications": [],
         "description": "Sit at the row machine with chest supported and pull handles toward you.\nA back-friendly alternative to free-weight rows."},
        {"name": "Deadlift", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 12, "contraindications": ["Back Pain"],
         "description": "Lift a loaded barbell from the floor to hip level keeping the back straight.\nDrive through the heels and hinge at the hips."},
        {"name": "Pull-Up", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 10, "contraindications": [],
         "description": "Hang from a bar and pull your chin above it using your back and arms.\nLower under control to full extension."},
    ],
    "Legs": [
        {"name": "Bodyweight Squat", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 7, "contraindications": [],
         "description": "Lower hips back and down keeping chest up, then drive back to standing.\nKeep knees tracking over toes."},
        {"name": "Glute Bridge", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 5, "contraindications": [],
         "description": "Lie on your back and lift hips toward the ceiling, squeezing glutes.\nLower with control and repeat."},
        {"name": "Stationary Cycling", "equipment": ["Full Gym"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 11, "contraindications": [],
         "description": "Pedal at a steady moderate pace on a stationary bike.\nLow-impact cardio that is gentle on the knees."},
        {"name": "Leg Extension", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Beginner",
         "base_cal": 6, "contraindications": [],
         "description": "Sit on the machine and extend your legs against resistance until straight.\nLower slowly, isolating the quads with minimal knee strain."},
        {"name": "Dumbbell Lunge", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 8, "contraindications": ["Knee Pain"],
         "description": "Step forward into a lunge, lowering the back knee toward the floor.\nPush through the front heel to return to standing."},
        {"name": "Leg Press", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 10, "contraindications": [],
         "description": "Push a weighted platform away using your legs while seated and supported.\nKeep knees aligned and avoid locking them out."},
        {"name": "Barbell Back Squat", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 12, "contraindications": ["Knee Pain", "Back Pain"],
         "description": "Squat down with a barbell across your upper back until thighs are parallel to the floor.\nDrive through the heels to stand back up."},
        {"name": "Jump Squat", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Advanced",
         "base_cal": 10, "contraindications": ["Knee Pain"],
         "description": "Squat down then explode upward into a jump, landing softly.\nA high-intensity plyometric move for power."},
        {"name": "Hamstring Curl (Machine)", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Beginner",
         "base_cal": 6, "contraindications": [],
         "description": "Lie face down and curl the leg pad toward your glutes.\nIsolates hamstrings with controlled, joint-friendly motion."},
    ],
    "Shoulders": [
        {"name": "Pike Push-Up", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 6, "contraindications": [],
         "description": "In a downward-dog position, bend elbows to lower your head toward the floor.\nPress back up to target the shoulders."},
        {"name": "Dumbbell Shoulder Press", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 8, "contraindications": [],
         "description": "Press dumbbells overhead from shoulder height until arms are extended.\nLower slowly back to the start position."},
        {"name": "Lateral Raise", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 5, "contraindications": [],
         "description": "Raise dumbbells out to the sides until arms are level with shoulders.\nKeep a slight bend in the elbows throughout."},
        {"name": "Band Face Pull", "equipment": ["Resistance Bands"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 5, "contraindications": [],
         "description": "Pull a band toward your face, flaring elbows out wide.\nStrengthens rear delts and improves posture."},
        {"name": "Machine Shoulder Press", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Beginner",
         "base_cal": 7, "contraindications": [],
         "description": "Press the handles overhead while seated with back supported.\nA joint-friendly alternative to barbell pressing."},
        {"name": "Barbell Overhead Press", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 9, "contraindications": [],
         "description": "Press a barbell from shoulder height to overhead while standing.\nBrace your core to protect the lower back."},
    ],
    "Arms": [
        {"name": "Bodyweight Tricep Dip", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 6, "contraindications": [],
         "description": "Using a bench or chair, lower your body by bending elbows then push back up.\nKeep elbows close to your body."},
        {"name": "Dumbbell Bicep Curl", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 5, "contraindications": [],
         "description": "Curl dumbbells toward your shoulders keeping elbows fixed at your sides.\nLower slowly to full extension."},
        {"name": "Band Tricep Pushdown", "equipment": ["Resistance Bands"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 5, "contraindications": [],
         "description": "Anchor a band overhead and push the handle down until arms are straight.\nKeep elbows pinned to your sides."},
        {"name": "Hammer Curl", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 5, "contraindications": [],
         "description": "Curl dumbbells with palms facing each other throughout the motion.\nTargets biceps and forearms together."},
        {"name": "Cable Tricep Pushdown", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 6, "contraindications": [],
         "description": "Push the cable bar downward until arms are fully extended.\nKeep elbows tucked and control the return."},
        {"name": "Skull Crusher", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 6, "contraindications": [],
         "description": "Lying on a bench, lower a barbell toward your forehead by bending elbows.\nExtend arms back up to target the triceps."},
    ],
    "Core": [
        {"name": "Plank", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 5, "contraindications": [],
         "description": "Hold a straight-body position supported on forearms and toes.\nKeep hips level and core braced."},
        {"name": "Bird Dog", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "On hands and knees, extend opposite arm and leg while keeping back flat.\nHold briefly then switch sides."},
        {"name": "Bicycle Crunch", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 6, "contraindications": ["Back Pain"],
         "description": "Alternate bringing elbow to opposite knee in a pedaling motion.\nKeep lower back pressed to the floor."},
        {"name": "Cable Woodchopper", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 7, "contraindications": ["Back Pain"],
         "description": "Rotate a cable handle diagonally across your body from high to low.\nEngages obliques through rotational movement."},
        {"name": "Hanging Leg Raise", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Advanced",
         "base_cal": 8, "contraindications": ["Back Pain"],
         "description": "Hang from a bar and raise your legs to hip height or higher.\nAvoid swinging and control the descent."},
        {"name": "Dead Bug", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "Lying on your back, lower opposite arm and leg toward the floor while bracing.\nA back-friendly way to build core stability."},
    ],
    "Cardio": [
        {"name": "Brisk Walking", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 8, "contraindications": [],
         "description": "Walk at a pace that raises your heart rate while staying able to talk.\nA low-impact way to build cardiovascular base."},
        {"name": "Jogging", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 12, "contraindications": ["Knee Pain"],
         "description": "Maintain a steady moderate-intensity run.\nFocus on relaxed shoulders and consistent breathing."},
        {"name": "Stationary Bike Intervals", "equipment": ["Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Intermediate", "base_cal": 13, "contraindications": [],
         "description": "Alternate between high and moderate resistance on a stationary bike.\nKnee-friendly way to elevate heart rate."},
        {"name": "Jumping Jacks", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 9, "contraindications": ["Knee Pain"],
         "description": "Jump feet out while raising arms overhead, then return to start.\nA full-body cardio movement to raise heart rate."},
        {"name": "Burpees", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Advanced",
         "base_cal": 14, "contraindications": ["Knee Pain", "Back Pain"],
         "description": "Drop into a squat, kick back into a plank, then jump explosively upward.\nA high-intensity full-body conditioning move."},
        {"name": "Rowing Machine", "equipment": ["Full Gym"], "location": ["Gym"], "difficulty": "Intermediate",
         "base_cal": 12, "contraindications": [],
         "description": "Drive with your legs then pull the handle toward your chest in a rowing motion.\nWorks the whole body while staying low-impact."},
        {"name": "Mountain Climbers", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 10, "contraindications": ["Back Pain"],
         "description": "From a plank position, drive knees alternately toward your chest quickly.\nKeeps hips low and core engaged throughout."},
    ],
    "Full Body": [
        {"name": "Kettlebell Swing", "equipment": ["Full Gym"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 11, "contraindications": ["Back Pain"],
         "description": "Hinge at the hips and swing the kettlebell to shoulder height using hip drive.\nEngages the posterior chain and core."},
        {"name": "Bodyweight Circuit (Squat-Push-Row)", "equipment": ["None"], "location": ["Gym", "Home"],
         "difficulty": "Beginner", "base_cal": 9, "contraindications": [],
         "description": "Cycle through squats, push-ups, and band rows with minimal rest.\nBuilds full-body endurance and strength together."},
        {"name": "Dumbbell Thruster", "equipment": ["Dumbbells", "Full Gym"], "location": ["Gym", "Home"],
         "difficulty": "Advanced", "base_cal": 12, "contraindications": ["Knee Pain"],
         "description": "Squat down then drive up explosively, pressing dumbbells overhead.\nCombines a squat and press into one powerful movement."},
    ],
    "Yoga": [
        {"name": "Downward Dog", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "Form an inverted V-shape with hips lifted and heels reaching toward the floor.\nStretches the hamstrings, calves, and shoulders."},
        {"name": "Warrior II Pose", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "Step into a wide stance with front knee bent and arms extended parallel to the floor.\nBuilds leg strength and hip mobility."},
        {"name": "Cat-Cow Flow", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 3, "contraindications": [],
         "description": "On hands and knees, alternate arching and rounding the spine with your breath.\nImproves spinal mobility and eases tension."},
        {"name": "Child's Pose", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 2, "contraindications": [],
         "description": "Sit back on your heels with arms extended forward and forehead resting down.\nA restorative pose that gently stretches the back and hips."},
        {"name": "Triangle Pose", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 4, "contraindications": ["Back Pain"],
         "description": "From a wide stance, hinge sideways to reach your hand toward your shin or floor.\nStretches the hamstrings, hips, and spine."},
        {"name": "Bridge Pose", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 4, "contraindications": [],
         "description": "Lying on your back, lift hips toward the ceiling while pressing feet into the floor.\nStrengthens glutes and opens the chest."},
        {"name": "Seated Forward Bend", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Beginner",
         "base_cal": 3, "contraindications": ["Back Pain"],
         "description": "Sit with legs extended and hinge forward from the hips reaching for your feet.\nStretches the hamstrings and lower back."},
        {"name": "Tree Pose", "equipment": ["None"], "location": ["Gym", "Home"], "difficulty": "Intermediate",
         "base_cal": 3, "contraindications": [],
         "description": "Balance on one leg with the other foot resting on the inner thigh or calf.\nImproves balance, focus, and hip stability."},
    ],
}

WARMUP = [
    {"name": "Arm Circles", "duration": "1 min", "description": "Rotate arms in large circles forward then backward to loosen shoulders."},
    {"name": "Bodyweight Squats", "duration": "1 min", "description": "Perform slow, controlled squats to warm up the hips and knees."},
    {"name": "High Knees", "duration": "1 min", "description": "Jog in place bringing knees up toward your chest to raise heart rate."},
    {"name": "Torso Twists", "duration": "1 min", "description": "Rotate your torso side to side to mobilize the spine."},
    {"name": "Light Jogging / Marching in Place", "duration": "3 min", "description": "Gradually raise heart rate and core temperature before training."},
]

WARMUP_LOW_IMPACT = [
    {"name": "Arm Circles", "duration": "1 min", "description": "Rotate arms in large circles forward then backward to loosen shoulders."},
    {"name": "Standing Marching", "duration": "2 min", "description": "March in place lifting knees gently to warm up without impact."},
    {"name": "Cat-Cow Stretch", "duration": "1 min", "description": "Alternate arching and rounding the back on hands and knees to mobilize the spine."},
    {"name": "Stationary Cycling (Easy Pace)", "duration": "3 min", "description": "Cycle at low resistance to gently raise heart rate and warm the knees."},
]

COOLDOWN = [
    {"name": "Standing Forward Fold", "duration": "1 min", "description": "Hinge at the hips and let your upper body hang to stretch the hamstrings."},
    {"name": "Deep Breathing", "duration": "2 min", "description": "Slow diaphragmatic breathing to lower heart rate and promote recovery."},
    {"name": "Walking Cooldown", "duration": "3 min", "description": "Walk at an easy pace to gradually bring your heart rate back down."},
]

STRETCHES = [
    {"name": "Quad Stretch", "duration": "30 sec/side", "description": "Pull heel toward glutes while standing to stretch the front of the thigh."},
    {"name": "Hamstring Stretch", "duration": "30 sec/side", "description": "Extend one leg forward and hinge at the hips to stretch the back of the thigh."},
    {"name": "Chest Opener Stretch", "duration": "30 sec", "description": "Clasp hands behind your back and lift slightly to open the chest."},
    {"name": "Shoulder Cross-Body Stretch", "duration": "30 sec/side", "description": "Pull one arm across your chest to stretch the shoulder."},
    {"name": "Child's Pose", "duration": "45 sec", "description": "Sit back on your heels with arms extended forward to stretch the back and hips."},
    {"name": "Cat-Cow Stretch", "duration": "45 sec", "description": "Alternate arching and rounding the spine on hands and knees for spinal mobility."},
]
